### ISSUE TITLE
Database should not be writable

### ISSUE THREAD

**Issue by lshep** [ju-mu/PANTHER.db#2]
There is some background in the [pull request](https://github.com/ju-mu/PANTHER.db/pull/1)  and see @hpages  [original suggested changes to zzz.R](https://github.com/Bioconductor/BiocFileCache/pull/19#issuecomment-551342243) that should eventually be implemented and your package should adjust to not ERROR.  Trying to change the connection type from  `AnnotationDbi::dbFileConnect()` instead of `DBI::dbConnect()` broke the package. 
```
PANTHER.db version 1.0.6
Quitting from lines 77-81 (PANTHER.db.Rmd) 
Error: processing vignette 'PANTHER.db.Rmd' failed with diagnostics:
attempt to write a readonly database
--- failed re-building 'PANTHER.db.Rmd'
```
It seems like at some point you write to your database.  SQLite-based annotation packages should never write to the SQLite file or try to modify their content/connection.  Please try and address this issue, changing the connection to use `AnnotationDbi::dbFileConnect()`  and adjusting the code appropriately.

**Comment by ju-mu** [comment]
Should be all fixed with version 1.0.10
